plugins {
    id("java")
    id("eclipse")
    id("idea")
    id("maven-publish")
    id("fabric-loom") version ("1.8-SNAPSHOT")
    id("me.modmuss50.mod-publish-plugin") version ("0.7.4")
}

val group: String by extra
val modId: String by extra
val minecraftVersion: String by extra
val minecraftVersionRangeStart: String by extra
val modGroup: String by extra
val curseHomepageUrl: String by extra
val curseProjectId: String by extra
val modrinthId: String by extra
val modJavaVersion: String by extra
val forgeVersion: String by extra
val curseforgeApikey: String? by project
val modrinthToken: String? by project
val modAuthor: String by extra
val modDescription: String by extra
val modName: String by extra
val forgeVersionRange: String by extra
val fabricLoaderVersion: String by extra
val fabricApiVersion: String by extra

val githubUrl: String by extra
val forgeLoaderVersionRange: String by extra
val minecraftVersionRange: String by extra

//adds the build number to the end of the version string if on a build server
var buildNumber = project.findProperty("BUILD_NUMBER")
if (buildNumber == null) {
    buildNumber = "9999"
}
var baseArchivesName = "${modId}-${minecraftVersion}.${buildNumber}"

base {
    archivesName.set(baseArchivesName)
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(modJavaVersion))
    }
}

dependencies {
    minecraft(
        group = "com.mojang",
        name = "minecraft",
        version = minecraftVersion,
    )
    mappings(loom.layered {
        officialMojangMappings()
    })
    modImplementation(
        group = "net.fabricmc",
        name = "fabric-loader",
        version = fabricLoaderVersion,
    )
    modImplementation(
        group = "net.fabricmc.fabric-api",
        name = "fabric-api",
        version = fabricApiVersion,
    )
    implementation(
        group = "com.google.code.findbugs",
        name = "jsr305",
        version = "3.0.1"
    )
}


var list = mutableListOf("common","fabric","resources")

// Include resources generated by data generators.
sourceSets {
    main {
        java {
            setSrcDirs(list)
        }
        resources {
            setSrcDirs(list)
        }
    }
}

publishMods {
    file.set(tasks.jar.get().archiveFile)
    changelog = "Nightly build"
    type = BETA
    modLoaders.add("fabric")
    displayName.set("${project.version}.${buildNumber}-$minecraftVersion-fabric")
    version.set(project.version.toString())

    curseforge {
        projectId = curseProjectId
        accessToken.set(curseforgeApikey ?: "0")
        changelog = "Nightly build"
        minecraftVersionRange {
            start = minecraftVersionRangeStart
            end = minecraftVersion
        }
        javaVersions.add(JavaVersion.toVersion(modJavaVersion))
    }

    modrinth {
        projectId = modrinthId
        accessToken.set(modrinthToken)
        minecraftVersionRange {
            start = minecraftVersionRangeStart
            end = minecraftVersion
        }
    }
}

tasks.withType<ProcessResources> {
    val properties = mapOf(
            "curseHomepageUrl" to curseHomepageUrl,
            "forgeVersionRange" to forgeVersionRange,
            "githubUrl" to githubUrl,
            "forgeLoaderVersionRange" to forgeLoaderVersionRange,
            "minecraftVersion" to minecraftVersion,
            "minecraftVersionRange" to minecraftVersionRange,
            "modAuthor" to modAuthor,
            "modDescription" to modDescription,
            "modId" to modId,
            "modJavaVersion" to modJavaVersion,
            "modName" to modName,
            "version" to version,
    )
    inputs.properties(properties)
    filesMatching(listOf("META-INF/mods.toml", "META-INF/neoforge.mods.toml", "pack.mcmeta", "fabric.mod.json")) {
        expand(properties)
    }
}

idea {
    module {
        for (fileName in listOf("build", "run", "out", "logs")) {
            excludeDirs.add(file(fileName))
        }
    }
}

artifacts {
    archives(tasks.jar.get())
}


tasks.jar {
    from(sourceSets.main.get().output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

// Required because FG, copied from the MDK
sourceSets.forEach {
    val outputDir = layout.buildDirectory.file("sourcesSets/${it.name}").get().asFile
    it.output.setResourcesDir(outputDir)
    it.java.destinationDirectory.set(outputDir)
}
