pipeline {
    agent any
    tools {
        jdk "jdk-21"
    }

    environment {
      ORG_GRADLE_PROJECT_curseforgeApikey = credentials("jei-curseforge-key")
      ORG_GRADLE_PROJECT_modrinthToken = credentials("modrinth-auth-token")
      ORG_GRADLE_PROJECT_BUILD_NUMBER = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Clean') {
            steps {
                echo 'Cleaning Project'
                sh 'chmod +x gradlew'
                sh './gradlew clean'
            }
        }

        stage('Build') {
            steps {
                sh "./gradlew build"
            }
        }

        stage('Publish Maven') {
            steps {
            }
        }

        stage('Publish CurseForge') {
            steps {
            }
        }

        stage('Publish Modrinth') {
            steps {
            }
        }

        stage('Archive') {
            steps {
                junit allowEmptyResults: true, testResults: '*/build/test-results/**/*.xml'
            }
        }
    }
}